services:
  - type: web
    name: welcome-ai-alt-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false